### PR TITLE
Segfault

### PR DESCRIPTION
**Pull request by craff**
Three solutions:

- We ask for ocaml >= 4.09 or 4.08 (did not test 4.08, but 4.07 does not work)
- We use normal global root
- We test OCaml version to use generational global root for recent version of OCaml

What do you think ?

### CODE REVIEW

**Comment by rlepigre** [comment]
I am not sure I understand the difference between normal global roots and generational global roots. But I'd say we should use normal global roots, as from what I understand the benefit of generational ones may not be very big. Or is it?

Otherwise we can require a more recent OCaml, I don't mind.

**Comment by craff** [comment]
The documentation say "better performance for root that are rarely modified" so I test and use generational root from 
version 4.09.

Seems to work. Ask review...

**Comment by craff** [comment]
By the way I tested, 4.08.1 does not work either. The Ocaml bug at play is

https://github.com/ocaml/ocaml/pull/8656

which was cherry picked for 4.09

**Review by rlepigre — APPROVED** [review]
OK, that seems fine to me.

However this branch contains a modified of the maze example that is not really finished. However I think it should be fine to merge with what I pushed right now (I also fixed a missing dep in the opam file which prevented pinning).

Things to improve with the mouse control are:
- Hide the cursor, and ensure that it cannot get outside te window while it has focus. (Maybe move it back to the center after a motion?)
- Ensure that the bottom of the camera remains parallel to the ground (to prevent it to get tilted to the side which is weird).
- Add better keyboard control: have the arrows control the movement: up moves forward in the direction of the camera, and back the same but backward, left and right move the point of view of the camera sideways.
- Add a second camera mode (and the option to switch between the two modes) where the camera is at a fixed level from the ground (i.e., head height) and the up/down keyboard keys move the camera forward parallel to the ground.

**Pull request merged**
